### PR TITLE
Display Project Tags on Discover Page

### PR DESCRIPTION
**Pull request by bellkelly**
There are a few things that I think could be improved upon in this MR, but I'm not sure if they should be logged as issues for future improvements or fixed now.

I wasn't sure where to put the tags, so I put them in the footer of the Project Cards. Things look pretty squished. Maybe this is something that could be addressed in the design meeting?

Screen Shot 2019-03-17 at 8 41 57 PM

Also, I think there's an oppertunity to improve efficiency by adding a `with_tags` param to the `GET projects` API call. Right now, we make one API call per project to get the tags. We could instead just get the projects with their tags in one API call and map them out into the Tags component. Just a thought.

### CODE REVIEW

**Comment by anisha-rohra** [comment]
@bellkelly did you test what the edit button looks like on top of all of this? It only appears when you're logged in as a user who owns a test on the discover page!

**Comment by F-Ting** [comment]
@bellkelly adding a query handler would be a good idea, let me look at getting that setup

**Comment by bellkelly** [comment]
@anisha-rohra, I haven't tested with a logged in user. What login credentials should I use?

**Comment by anisha-rohra** [comment]
@bellkelly you'd have to fetch from master I just realized because its likely your repo doesn't have the edit button right now, and then login as any of the users that show up under /api/users with password as the password

**Comment by bellkelly** [comment]
Thanks @anisha-rohra! I tested it out and it does kind of mess up the edit button position 😞  I've thought of three ways to improve this, but maybe there's a better alternative:

1. Increase the size of the project cards. I'm not sure if we want this? Maybe increase the width so that there's three per row and increase the height a bit?
2. Put the tags in the description, but then they will be hidden below the description text and users would have to scroll through the description to see them
3. Display one row of tags and have the ability to scroll horizontally (just like how the description scrolls vertically). This might need a small bump in the height of the cards and it hides tags users might care about.

I'm inclined to do 1 if everyone else thinks that's ok, but I'm also open to other ideas.

**Comment by F-Ting** [comment]
@bellkelly does the JSON format in issue #54 looks good to you to be used for displaying?

**Comment by anisha-rohra** [comment]
@bellkelly 1 sounds fine with me!

**Comment by bellkelly** [comment]
Ok, I updated the styles a bit. I think it looks a bit better now? 

Screen Shot 2019-03-18 at 9 32 18 PM

**Comment by anisha-rohra** [comment]
Yeah, this looks great!

**Review by anisha-rohra — APPROVED** [review]

**Pull request merged**
